baseURL = 'https://krisrp.dev'
languageCode = 'en-us'
title = 'Somewhere in the middle'
theme = 'nightfall'

[params.meta]
  favicon   = true

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

[params]
author = "Kris Pamungkas"
user = "kris"
hostname = "r00t"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

